#!/usr/bin/env python3
import pty
import os
import sys
import subprocess


def main():
    master, slave = pty.openpty()
    if len(sys.argv) > 1:
        pid = os.fork()
        if pid == 0:  # Child process
            os.close(master)
            os.dup2(slave, 1)
            os.dup2(slave, 2)
            os.execvp(sys.argv[1], sys.argv[1:])
        os.close(slave)
    else:
        os.write(slave, sys.stdin.buffer.read())
        os.close(slave)

    output = b""
    while True:
        try:
            data = os.read(master, 1024)
            if not data:
                break
            output += data
        except OSError:
            break
    os.close(master)
    less_process = subprocess.Popen(["less", "-R"], stdin=subprocess.PIPE)
    less_process.communicate(input=output)


if __name__ == "__main__":
    main()
